
#配置mybatisplus数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dianba?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 15374583460qq
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis-plus配置 sql执行日志文件
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8081